name = "EvolutionModel"
uuid = "7cc1457e-611b-11e9-39b8-c321eb471a5b"
authors = ["Long Wang <wangl.cc@outlook.com>"]
version = "0.1.0"

[extras]
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
HypothesisTests = "09f84164-cd44-5f33-b23f-e6b0d136a0d5"

[targets]
test = ["Distributions", "HypothesisTests"]
